quarkus:
  thread-pool:
    core-threads: 10
    max-threads: 10
  datasource:
    devservices:
      image-name: ghcr.io/quarkusio/postgres-17-perf:main
  jackson:
    serialization-inclusion: non-empty
  rest:
    jackson:
      optimization:
        # See https://quarkus.io/blog/quarkus-metaprogramming/
        enable-reflection-free-serializers: true

"%prod":
  quarkus:
    datasource:
      username: fruits
      password: fruits
      jdbc:
        url: jdbc:postgresql://localhost:5432/fruits
